---
# Traefik Reverse Proxy Configuration

# Traefik Version
traefik_version: "v3.0"

# Traefik Directories
traefik_root_dir: "{{ docker_stack_root }}/traefik"
traefik_data_dir: "{{ traefik_root_dir }}/traefik-data"
traefik_config_dir: "{{ traefik_root_dir }}/traefik-config"

# Network Configuration
traefik_network_name: "app-network"

# Let's Encrypt Configuration
traefik_acme_email: "{{ vault_traefik_acme_email | default('admin@example.com') }}"

# Logging
traefik_log_level: "INFO"

# Error Pages Configuration
traefik_error_pages:
  - code: "400"
    title: "Bad Request"
    message: "The request could not be understood by the server due to malformed syntax. Please check your request and try again."
    color: "#ef4444"
  - code: "401"
    title: "Unauthorized"
    message: "Authentication is required to access this resource. Please provide valid credentials and try again."
    color: "#f59e0b"
  - code: "403"
    title: "Forbidden"
    message: "You don't have permission to access this resource. Contact the administrator if you believe this is an error."
    color: "#dc2626"
  - code: "404"
    title: "Page Not Found"
    message: "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable. Please check the URL for any typos or navigate back to the homepage."
    color: "#ff6b47"
  - code: "500"
    title: "Internal Server Error"
    message: "The server encountered an unexpected condition that prevented it from fulfilling the request. Please try again later."
    color: "#dc2626"
  - code: "502"
    title: "Bad Gateway"
    message: "The server received an invalid response from the upstream server. This is usually a temporary issue."
    color: "#7c3aed"
  - code: "503"
    title: "Service Unavailable"
    message: "The service is temporarily unavailable due to maintenance or overload. Please try again later."
    color: "#059669"
  - code: "504"
    title: "Gateway Timeout"
    message: "The server did not receive a timely response from the upstream server. Please try again later."
    color: "#0d9488"

# UFW Firewall Rules (automatically applied by role)
traefik_ufw_rules:
  - port: "80"
    proto: "tcp"
    comment: "Traefik HTTP"
  - port: "443"
    proto: "tcp"
    comment: "Traefik HTTPS" 