apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb
  - traefik
  - argocd
  - argo-rollouts
  - argo-workflows
  - argo-events
  - harbor
  - rook-ceph
  - rook-ceph-cluster
