services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - app-network
    
    volumes:
      - vaultwarden_data:/data
    
    environment:
      DOMAIN: "https://vw.gooffy.in"
      SIGNUPS_ALLOWED: "true"
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        # Traefik configuration for public access
        - traefik.enable=true
        - traefik.http.routers.vaultwarden.rule=Host(`vw.gooffy.in`)
        - traefik.http.routers.vaultwarden.entrypoints=websecure
        - traefik.http.routers.vaultwarden.tls.certresolver=cloudflare
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    
networks:
  app-network:
    external: true

volumes:
  vaultwarden_data:
    driver: local