---
# Docker Configuration Role - Handlers
# Manages systemd daemon reload and Docker service restart

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "reload systemd"

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  listen: "restart docker" 