---
# Kernel Hardening Role - Main Tasks
# Applies kernel security parameters and system limits

- name: Create sysctl security configuration
  ansible.builtin.template:
    src: 99-security-hardening.conf.j2
    dest: /etc/sysctl.d/99-security-hardening.conf
    mode: '0644'
    owner: root
    group: root
    backup: true
  register: sysctl_config_created
  when: kernel_hardening_enabled | default(true)
  notify:
    - reload sysctl
  tags:
    - kernel_hardening
    - sysctl

- name: Apply sysctl configuration immediately
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ kernel_security_params | dict2items }}"
  when: kernel_hardening_enabled | default(true)
  tags:
    - kernel_hardening
    - sysctl

- name: Create system limits configuration
  ansible.builtin.template:
    src: 99-docker-limits.conf.j2
    dest: /etc/security/limits.d/99-docker-limits.conf
    mode: '0644'
    owner: root
    group: root
    backup: true
  when: system_limits_enabled | default(true)
  tags:
    - kernel_hardening
    - limits

- name: Verify kernel parameters are applied
  ansible.builtin.command: sysctl {{ item.key }}
  register: sysctl_verification
  changed_when: false
  failed_when: sysctl_verification.stdout.split('=')[1].strip() != (item.value | string)
  loop: "{{ kernel_security_params | dict2items }}"
  when: kernel_hardening_enabled | default(true)
  tags:
    - kernel_hardening
    - validation

- name: Display kernel hardening summary
  ansible.builtin.debug:
    msg:
      - "Kernel hardening configuration applied"
      - "Sysctl config: /etc/sysctl.d/99-security-hardening.conf"
      - "System limits: /etc/security/limits.d/99-docker-limits.conf"
      - "Parameters applied: {{ kernel_security_params | length }}"
      - "System limits configured: {{ system_limits | length }}"
      - "IP forwarding (Docker): {{ kernel_security_params['net.ipv4.ip_forward'] }}"
      - "File descriptor limit: {{ docker_file_limits }}"
  tags:
    - kernel_hardening
    - summary

- name: Check if reboot is recommended
  ansible.builtin.set_fact:
    kernel_reboot_recommended: true
  when: sysctl_config_created is changed
  tags:
    - kernel_hardening 