---
# CrowdSec Security Engine Role - Handlers
# Manages CrowdSec service restarts and configuration reloads

- name: restart crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted
    daemon_reload: true
  listen: "restart crowdsec"

- name: restart crowdsec-firewall-bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
    daemon_reload: true
  listen: "restart crowdsec-firewall-bouncer"

- name: reload crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: reloaded
  listen: "reload crowdsec" 