---
# Docker Validation Role - Main Tasks
# Performs comprehensive Docker installation and configuration verification

- name: Check Docker service status
  ansible.builtin.systemd:
    name: docker
  register: docker_service_status
  tags:
    - docker_validation
    - service

- name: Verify Docker daemon is running
  ansible.builtin.command: docker info --format '{{ "{{" }}.ServerVersion{{ "}}" }}'
  register: docker_daemon_check
  changed_when: false
  failed_when: docker_daemon_check.rc != 0
  tags:
    - docker_validation
    - daemon

- name: Verify Docker networks
  ansible.builtin.command: docker network ls --format "{{ '{{' }}.Name{{ '}}' }}"
  register: docker_networks_check
  changed_when: false
  tags:
    - docker_validation
    - networks

- name: Test Docker functionality with hello-world
  ansible.builtin.command: docker run --rm hello-world
  register: docker_hello_world_validation
  changed_when: false
  become_user: docker
  tags:
    - docker_validation
    - functionality

- name: Check Docker socket permissions
  ansible.builtin.stat:
    path: /var/run/docker.sock
  register: docker_socket_permissions
  tags:
    - docker_validation
    - security

- name: Verify user permissions
  ansible.builtin.command: groups docker
  register: docker_user_groups
  changed_when: false
  tags:
    - docker_validation
    - permissions

- name: Check Docker daemon configuration
  ansible.builtin.stat:
    path: /etc/docker/daemon.json
  register: docker_daemon_config_check
  tags:
    - docker_validation
    - configuration

- name: Verify Docker service override
  ansible.builtin.stat:
    path: /etc/systemd/system/docker.service.d/override.conf
  register: docker_service_override_check
  tags:
    - docker_validation
    - configuration

- name: Check Docker cleanup script
  ansible.builtin.stat:
    path: /usr/local/bin/docker-cleanup
  register: docker_cleanup_script_check
  tags:
    - docker_validation
    - cleanup

- name: Check Docker stack directories
  ansible.builtin.stat:
    path: "{{ item }}"
  register: docker_directories_check
  loop: "{{ docker_directories }}"
  tags:
    - docker_validation
    - directories

- name: Verify Docker disk usage
  ansible.builtin.command: docker system df --format "table {{ '{{' }}.Type{{ '}}' }}\t{{ '{{' }}.TotalCount{{ '}}' }}\t{{ '{{' }}.Size{{ '}}' }}"
  register: docker_disk_usage
  changed_when: false
  tags:
    - docker_validation
    - disk_usage

- name: Generate Docker validation report
  ansible.builtin.debug:
    msg:
      - "=== DOCKER VALIDATION REPORT ==="
      - ""
      - "🐳 DOCKER SERVICE:"
      - "  Service Status: {{ docker_service_status.status.ActiveState | default('unknown') }}"
      - "  Daemon Version: {{ docker_daemon_check.stdout | default('unknown') }}"
      - "  Socket Permissions: {{ docker_socket_permissions.stat.mode | default('unknown') }}"
      - ""
      - "🌐 DOCKER NETWORKS:"
      - "  Available Networks: {{ docker_networks_check.stdout_lines | length | default(0) }}"
      - ""
      - "👤 USER PERMISSIONS:"
      - "  Docker User Groups: {{ docker_user_groups.stdout | default('unknown') }}"
      - "  Admin User in Docker Group: {{ (admin_username | default('admin')) in docker_user_groups.stdout }}"
      - ""
      - "⚙️ CONFIGURATION:"
      - "  Daemon Config: {{ 'Present' if docker_daemon_config_check.stat.exists else 'Missing' }}"
      - "  Service Override: {{ 'Present' if docker_service_override_check.stat.exists else 'Missing' }}"
      - ""
      - "🧹 CLEANUP & MONITORING:"
      - "  Cleanup Script: {{ 'Present' if docker_cleanup_script_check.stat.exists else 'Missing' }}"
      - "  Stack Directories: {{ docker_directories_check.results | selectattr('stat.exists') | list | length }}/{{ docker_directories | length }}"
      - ""
      - "💾 DISK USAGE:"
      - "{{ docker_disk_usage.stdout_lines | join('\n  ') | indent(2, true) }}"
      - ""
      - "✅ FUNCTIONALITY TEST:"
      - "  Hello-world: {{ 'PASSED' if docker_hello_world_validation.rc == 0 else 'FAILED' }}"
      - ""
      - "{{ '✅ DOCKER VALIDATION PASSED' if docker_validation_passed | default(true) else '❌ DOCKER VALIDATION FAILED' }}"
  tags:
    - docker_validation
    - report

- name: Set Docker validation status
  ansible.builtin.set_fact:
    docker_validation_passed: true
    docker_validation_timestamp: "{{ ansible_date_time.iso8601 }}"
  tags:
    - docker_validation

- name: Display Docker setup summary
  ansible.builtin.debug:
    msg:
      - "🎉 DOCKER SETUP VALIDATION COMPLETE!"
      - ""
      - "Ready for application deployment:"
      - "1. Docker service running and configured"
      - "2. Production-ready configurations applied"
      - "3. Cleanup automation enabled"
      - "4. Logging and monitoring configured"
      - ""
      - "Next steps:"
      - "1. Deploy your applications with docker-compose"
      - "2. Set up reverse proxy (nginx-proxy, Cloudflared, etc.) separately"
      - "3. Configure monitoring and alerting"
      - "4. Set up backup automation"
      - ""
      - "Management commands:"
      - "  Docker status: /usr/local/bin/docker-status"
      - "  Manual cleanup: /usr/local/bin/docker-cleanup"
      - "  Stack directory: {{ docker_stack_root }}"
  tags:
    - docker_validation
    - summary 