---
# Docker Installation Role - Handlers
# Manages Docker service restarts and initialization

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  listen: "restart docker" 