---
services:
  frigate:
    build:
      context: .
      dockerfile: Dockerfile.frigate
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    env_file:
      - .env
    
    environment:
      - TZ=UTC
    volumes:
      - /mnt/Data/Shared_Storage/Rishi/Selfhosted/config/frigate-config:/config
      - /mnt/Data/Shared_Storage/Rishi/Selfhosted/data/cctv:/media/frigate
    ports:
      - "5000:5000"        # Keep for RTMP streams and API access
      - "8554:8554"  # Keep for RTSP restreaming
    
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # Web interface routing - HTTP
      - "traefik.http.routers.frigate-http.rule=Host(`${FRIGATE_DOMAIN}`)"
      - "traefik.http.routers.frigate-http.entrypoints=web"
      - "traefik.http.routers.frigate-http.service=frigate"
      
      # Web interface routing - HTTPS  
      - "traefik.http.routers.frigate-https.rule=Host(`${FRIGATE_DOMAIN}`)"
      - "traefik.http.routers.frigate-https.entrypoints=websecure"
      - "traefik.http.routers.frigate-https.tls=true"
      - "traefik.http.routers.frigate-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frigate-https.service=frigate"
      
      # Service configuration (Frigate web interface on port 5000)
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
    
    networks:
      - home-network

networks:
  home-network:
    external: true
