mqtt:
  enabled: false

tls:
  enabled: false

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

objects:
  track:
    - person
    - car
    - motorcycle

record:
  enabled: true
  retain:
    days: 3
    mode: active_objects
  alerts:
    retain:
      days: 7
      mode: active_objects
  detections:
    retain:
      days: 7
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  camera_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${CAMERA_USER_1}:${CAMERA_PASS_1}@${CAMERA_IP_1}:554/Streaming/channels/101
          roles:
            - detect
      hwaccel_args: preset-nvidia
    detect:
      enabled: true
      width: 960
      height: 1080

  camera_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${CAMERA_USER_1}:${CAMERA_PASS_1}@${CAMERA_IP_1}:554/Streaming/channels/201
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia
    detect:
      enabled: true
      width: 960
      height: 1080

  camera_3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${CAMERA_USER_1}:${CAMERA_PASS_1}@${CAMERA_IP_1}:554/Streaming/channels/301
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia
    detect:
      enabled: true
      width: 960
      height: 1080

  camera_4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${CAMERA_USER_1}:${CAMERA_PASS_1}@${CAMERA_IP_1}:554/Streaming/channels/401
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia
    detect:
      enabled: true
      width: 960
      height: 1080

  camera_5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${CAMERA_USER_2}:${CAMERA_PASS_2}@${CAMERA_IP_2}:554/stream1
          roles:
            - audio
            - detect
            - record
      hwaccel_args: preset-nvidia
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - speech
        - yell
    detect:
      enabled: true
      width: 640
      height: 360

version: 0.15-1
