---
# Whalewall Role - Main Tasks
# Handles Whalewall Docker container deployment for UFW/Docker firewall integration

- name: Check if Whalewall container is running
  ansible.builtin.shell: docker ps --format "table {{ '{{' }}.Names{{ '}}' }}" | grep whalewall || echo "not_running"
  register: whalewall_container_check
  changed_when: false
  tags:
    - whalewall
    - check

- name: Create Whalewall data volume
  ansible.builtin.shell: docker volume create whalewall_data
  when: '"not_running" in whalewall_container_check.stdout'
  register: whalewall_volume_created
  tags:
    - whalewall
    - volume

- name: Deploy Whalewall container
  ansible.builtin.shell: |
    docker run -d \
      --name whalewall \
      --cap-add NET_ADMIN \
      --network host \
      --restart unless-stopped \
      -v whalewall_data:/data \
      -v /var/run/docker.sock:/var/run/docker.sock:ro \
      ghcr.io/capnspacehook/whalewall:latest
  when: '"not_running" in whalewall_container_check.stdout'
  register: whalewall_deployed
  tags:
    - whalewall
    - deployment

- name: Wait for Whalewall to be ready
  ansible.builtin.pause:
    seconds: 10
  when: whalewall_deployed is changed
  tags:
    - whalewall
    - deployment

- name: Verify Whalewall container status
  ansible.builtin.shell: docker ps --filter "name=whalewall" --format "table {{ '{{' }}.Names{{ '}}' }}\t{{ '{{' }}.Status{{ '}}' }}"
  register: whalewall_status_check
  changed_when: false
  tags:
    - whalewall
    - verification

- name: Check Whalewall logs for any errors
  ansible.builtin.shell: docker logs whalewall --tail 20
  register: whalewall_logs
  changed_when: false
  when: whalewall_deployed is changed
  tags:
    - whalewall
    - verification

- name: Test Whalewall functionality
  ansible.builtin.shell: docker exec whalewall whalewall --help || echo "help_not_available"
  register: whalewall_help_test
  changed_when: false
  ignore_errors: true
  tags:
    - whalewall
    - testing

- name: Display Whalewall deployment summary
  ansible.builtin.debug:
    msg:
      - "Whalewall container deployment completed"
      - "Container status: {{ whalewall_status_check.stdout }}"
      - "Image: ghcr.io/capnspacehook/whalewall:latest"
      - "Capabilities: NET_ADMIN"
      - "Network mode: host"
      - "Data volume: whalewall_data"
      - "Docker socket: mounted read-only"
      - "UFW/Docker integration: active"
  tags:
    - whalewall
    - summary 