---
services:

  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:release
    
    # Environment configuration
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=immich-database
      - DB_USERNAME=immich
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich-redis
    
    volumes:
      - /mnt/Data/Shared_Storage/Rishi/Selfhosted/data/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # Web interface routing - HTTP
      - "traefik.http.routers.immich-http.rule=Host(`${IMMICH_DOMAIN}`)"
      - "traefik.http.routers.immich-http.entrypoints=web"
      - "traefik.http.routers.immich-http.service=immich"
      
      # Web interface routing - HTTPS  
      - "traefik.http.routers.immich-https.rule=Host(`${IMMICH_DOMAIN}`)"
      - "traefik.http.routers.immich-https.entrypoints=websecure"
      - "traefik.http.routers.immich-https.tls=true"
      - "traefik.http.routers.immich-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.immich-https.service=immich"
      
      # Service configuration (Immich web interface on port 2283)
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      
      # Middleware for large file uploads (50GB max)
      - "traefik.http.middlewares.immich-uploads.buffering.maxRequestBodyBytes=50000000000"  # 50GB
      - "traefik.http.middlewares.immich-uploads.buffering.maxResponseBodyBytes=50000000000" # 50GB
      - "traefik.http.middlewares.immich-uploads.buffering.memRequestBodyBytes=1048576"     # 1MB
      - "traefik.http.middlewares.immich-uploads.buffering.memResponseBodyBytes=1048576"    # 1MB
      
      # HTTP to HTTPS redirect
      - "traefik.http.middlewares.immich-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.immich-http.middlewares=immich-redirect"
      
      # Apply middleware to HTTPS router
      - "traefik.http.routers.immich-https.middlewares=immich-uploads"
      
      # Network specification for Traefik
      - "traefik.docker.network=home-network"
    
    networks:
      - home-network
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    
    volumes:
      - /mnt/Data/Shared_Storage/Rishi/Selfhosted/config/immich-config/ml-cache:/cache
    networks:
      - home-network
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      home-network:
        aliases:
          - redis
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      home-network:
        aliases:
          - database

networks:
  home-network:
    external: true

volumes:
  immich-postgres-data:
