---
# Cloudflared Handlers

- name: restart cloudflared
  become_user: "{{ admin_username }}"
  community.docker.docker_compose_v2:
    project_src: "{{ cloudflared_root_dir }}"
    state: present
    restarted: true
  listen: "restart cloudflared"

- name: reload cloudflared
  become_user: "{{ admin_username }}"
  community.docker.docker_compose_v2:
    project_src: "{{ cloudflared_root_dir }}"
    state: present
    recreate: smart
  listen: "reload cloudflared" 