---
# Stage 2: Production Inventory - Tailscale + Admin User
# Use this after system setup and admin user creation
# Final production-ready configuration

all:
  children:
    production_servers:
      hosts:
        server:
          ansible_host: "{{ vault_production_host }}"  # Tailscale hostname or public IP
          node_type: server

  vars:
    # Production connection settings (admin user via Tailscale or public IP)
    ansible_user: "{{ vault_production_user }}"  # Admin user
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default(omit) }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=10'
    
    # Passwordless sudo configured for admin user
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    # No become password needed
    
    ansible_python_interpreter: /usr/bin/python3 