---
# Stage 1: System Setup Inventory - Complete system setup
# Use this for the initial connection to Ubuntu server with SSH keys
# Includes user creation, system hardening, and Docker installation

all:
  children:
    system_servers:
      hosts:
        server:
          ansible_host: "{{ vault_bootstrap_host }}"  # Direct IP for initial setup
          node_type: server

  vars:
    # System setup connection settings (SSH keys)
    ansible_user: "{{ vault_bootstrap_user }}"  # Original user (ubuntu/root)
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default(omit) }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=10'
    
    # Passwordless sudo configured for base user
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    
    ansible_python_interpreter: /usr/bin/python3 