---
# Nginx Proxy Handlers

- name: restart nginx-proxy
  become_user: "{{ admin_username }}"
  community.docker.docker_compose_v2:
    project_src: "{{ nginx_proxy_root_dir }}"
    state: present
    restarted: true
  listen: "restart nginx-proxy"

- name: reload nginx-proxy
  become_user: "{{ admin_username }}"
  community.docker.docker_compose_v2:
    project_src: "{{ nginx_proxy_root_dir }}"
    state: present
    recreate: smart
  listen: "reload nginx-proxy" 