---
all:
  children:
    docker_servers:
      hosts:
        server:
          ansible_host: "{{ vault_ansible_init_host }}"  # Start with initial IP
          node_type: server

  vars:
    # Bootstrap connection settings (will be dynamically updated by playbook)
    ansible_user: "{{ vault_ansible_init_user }}"  # Start with initial user (ubuntu)
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default(omit) }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=10'
    ansible_ssh_pass: "{{ vault_ansible_init_password | default(omit) }}"  # Initial password
    
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    ansible_become_password: "{{ vault_ansible_init_password | default(omit) }}"
    
    ansible_python_interpreter: /usr/bin/python3 
    
    # Server Connection Configuration (loaded from vault.yml)
    server_public_ip: "{{ vault_server_public_ip }}"
    tailscale_magic_dns_suffix: "{{ vault_tailscale_magic_dns_suffix }}" 