services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - TZ=Asia/Kolkata
    labels:
      - "traefik.enable=false"
      # Watchtower best practice: opt-in rather than opt-out
      - "com.centurylinklabs.watchtower.enable=true"