---
# MergerFS Configuration for Home Server
# Provides unified storage pool from multiple drives

# MergerFS Installation
mergerfs_version: "2.40.2"
mergerfs_architecture: "amd64"  # or arm64 for ARM systems
mergerfs_debian_codename: "{{ ansible_distribution_release }}"

# Storage Configuration
mergerfs_pool_path: "/srv/storage"
mergerfs_mount_base: "/mnt"
mergerfs_drive_prefix: "disk"

# MergerFS Mount Options
mergerfs_mount_options:
  - "defaults"
  - "nonempty" 
  - "allow_other"
  - "use_ino"
  - "moveonenospc=true"
  - "dropcacheonclose=true"
  - "category.create=mspmfs"
  - "minfreespace=10G"
  - "fsname=mergerfs"

# Drive Configuration
mergerfs_filesystem: "ext4"
mergerfs_mount_opts: "defaults,noatime"

# Interactive Configuration
mergerfs_interactive_mode: true
mergerfs_auto_format: false  # Set to true to skip formatting prompts (DANGEROUS)
mergerfs_confirm_destructive: true  # Require confirmation for destructive operations

# Pool Structure
mergerfs_create_subdirs: true
mergerfs_subdirectories:
  - "media/movies"
  - "media/tv" 
  - "media/music"
  - "media/photos"
  - "downloads"
  - "backups"

# Permissions
mergerfs_pool_owner: "{{ admin_username }}"
mergerfs_pool_group: "{{ admin_username }}"
mergerfs_pool_mode: "0775"

# Validation Settings
mergerfs_verify_setup: true
mergerfs_test_files: true

# Drive Detection Settings
mergerfs_exclude_devices:
  - "loop"
  - "sr"
  - "fd"
  - "ram"
  - "dm-"
mergerfs_exclude_mount_points:
  - "/"
  - "/boot"
  - "/boot/efi"
  - "/home"
  - "/var"
  - "/tmp"
  - "/usr"
  - "/opt"
mergerfs_min_drive_size_gb: 10  # Minimum drive size to consider 