---
# Nginx Proxy Configuration for Home Server
# Replaces Traefik for local .home domain routing

# Nginx Proxy Version
nginx_proxy_version: "latest"

# Nginx Proxy Directories
nginx_proxy_root_dir: "{{ docker_stack_root }}/nginx-proxy"
nginx_proxy_config_dir: "{{ nginx_proxy_root_dir }}/conf.d"
nginx_proxy_ssl_dir: "{{ nginx_proxy_root_dir }}/certs"

# Network Configuration
nginx_proxy_network_name: "home-network"
nginx_proxy_internal_port: 80
nginx_proxy_host_ip: "127.0.0.1"

# Domain Configuration
domain_suffix: "home"
default_host: "home.local"

# Security Configuration
nginx_proxy_enable_ssl: false  # No SSL needed for local .home domains
nginx_proxy_trust_downstream: true

# Client Configuration
nginx_proxy_client_max_body_size: "100m"
nginx_proxy_proxy_read_timeout: "600s"
nginx_proxy_proxy_send_timeout: "600s"

# Custom Configuration
nginx_proxy_custom_config: |
  # Custom nginx configuration for .home domains
  # Disable SSL redirects for local development
  server_tokens off;
  
  # Increase buffer sizes for large requests
  proxy_buffer_size 128k;
  proxy_buffers 4 256k;
  proxy_busy_buffers_size 256k;
  
  # Timeout settings
  proxy_connect_timeout 60s;
  proxy_send_timeout 600s;
  proxy_read_timeout 600s;
  
  # Real IP configuration for Docker networks
  real_ip_header X-Forwarded-For;
  set_real_ip_from 172.16.0.0/12;
  set_real_ip_from 192.168.0.0/16;
  set_real_ip_from 10.0.0.0/8;

# No UFW rules needed - nginx-proxy only binds to localhost
# External access is handled by cloudflared tunnel 