services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    
    # Environment configuration
    env_file:
      - .env
    
    command:
      # API and Dashboard
      - --api.dashboard=false
      
      # Entry points
      - --entrypoints.web.address=:80
      
      # Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=home-network
      
      # Logging
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --accesslog=true

    ports:
      - "80:80"

    volumes:
      # Docker socket for service discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro


    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - local-network
    
# Networks
networks:
  local-network:
    external: true