---
# Time Sync Role - Main Tasks
# Configures Chrony for accurate time synchronization

- name: Stop and disable systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  when: chrony_replace_timesyncd | default(true)
  ignore_errors: true
  tags:
    - time_sync
    - chrony

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
  register: chrony_installed
  tags:
    - time_sync
    - chrony

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'
    owner: root
    group: root
    backup: true
  register: chrony_configured
  notify:
    - restart chrony
  tags:
    - time_sync
    - chrony

- name: Enable and start chrony service
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: started
  when: chrony_enabled | default(true)
  tags:
    - time_sync
    - chrony

- name: Wait for chrony to synchronize
  ansible.builtin.wait_for:
    timeout: 30
  when: chrony_configured is changed
  tags:
    - time_sync
    - chrony

- name: Check chrony tracking status
  ansible.builtin.command: chronyc tracking
  register: chrony_tracking
  changed_when: false
  tags:
    - time_sync
    - validation

- name: Check chrony sources
  ansible.builtin.command: chronyc sources -v
  register: chrony_sources
  changed_when: false
  tags:
    - time_sync
    - validation

- name: Display chrony status
  ansible.builtin.debug:
    msg:
      - "Chrony time synchronization configured"
      - "Service status: {{ 'enabled' if chrony_enabled else 'disabled' }}"
      - "NTP servers: {{ chrony_servers | join(', ') }}"
      - "Tracking status available in debug output"
  tags:
    - time_sync
    - summary

- name: Display chrony tracking details
  ansible.builtin.debug:
    var: chrony_tracking.stdout_lines
  tags:
    - time_sync
    - validation

- name: Display chrony sources details
  ansible.builtin.debug:
    var: chrony_sources.stdout_lines
  tags:
    - time_sync
    - validation 